### ISSUE TITLE
Series/ Movies related

### ISSUE THREAD

**Issue by KercsiBence** [evoCampus/evowatch-backend#8]
- [ ] evoCampus/evowatch-backend/issues/3 Create sereies DBO
- [ ] evoCampus/evowatch-backend/issues/5 Create sereies DTO
- [ ] evoCampus/evowatch-backend/issues/9 Create controller for series
- [ ] evoCampus/evowatch-backend/issues/10 Create service for series
- [ ] evoCampus/evowatch-backend/issues/11 Update database with new migration about series modell

**Comment by andraspazman** [comment]
We created the series controller , services, dbo, dto, repository
